version: '3'
services:
  web:
    restart: always
    build: .
    command: python ./app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mongo
      - db
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
 
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'MarchMadness'
      MYSQL_USER: 'march_madness'
      MYSQL_PASSWORD: 'a2JwtCyZxgQf8T7F'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3307:3306'
    volumes:
      - ./project/mysql/init_db:/docker-entrypoint-initdb.d

  celery:
    build: .
    command: celery worker -A project.celery_worker.celery -l info
    volumes:
      - .:/app
 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"