version: '3'
services:
  web:
    restart: always
    build: .
    command: python3 ./app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mongo
      - db
      - redis
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'MarchMadness'
      MYSQL_USER: 'march_madness'
      MYSQL_PASSWORD: 'a2JwtCyZxgQf8T7F'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ./project/mysql/init_db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
  celery:
    restart: always
    build: .
    command: celery worker -A project.celery_worker.celery -l info
    volumes:
      - .:/app
  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  db_data:
