version: '2.1'
services:
  web:
    restart: always
    network_mode: host
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
